version: '3'
services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../:/app
    environment:
      # below not used but keeping as a reference
      - APP_ENV=development
